### ISSUE TITLE
Build failure on AzureDevOps

### ISSUE THREAD

**Issue by Eskibear** [microsoft/vscode-java-dependency#170]
Build failure on clean AzureDevOps pipeline. I'm not sure if it's due to the p2 server. Please take some time to investigate in case there's any code defects.

Error log:
```
Downloaded from central: https://repo.maven.apache.org/maven2/org/apache/maven/plugins/maven-site-plugin/3.3/maven-site-plugin-3.3.jar (124 kB at 2.7 MB/s)
[INFO] Computing target platform for MavenProject: com.microsoft.jdtls.ext:com.microsoft.jdtls.ext.core:0.5.1 @ /mnt/a/1/s/jdtls.ext/com.microsoft.jdtls.ext.core/pom.xml
[INFO] Resolving dependencies of MavenProject: com.microsoft.jdtls.ext:com.microsoft.jdtls.ext.core:0.5.1 @ /mnt/a/1/s/jdtls.ext/com.microsoft.jdtls.ext.core/pom.xml
[INFO] {osgi.os=linux, osgi.ws=gtk, org.eclipse.update.install.features=true, osgi.arch=x86_64}
[ERROR] Cannot resolve project dependencies:
[ERROR]   Software being installed: com.microsoft.jdtls.ext.core 0.5.1
[ERROR]   Missing requirement: com.microsoft.jdtls.ext.core 0.5.1 requires 'bundle org.eclipse.core.runtime 0.0.0' but it could not be found
[ERROR] 
[ERROR] See http://wiki.eclipse.org/Tycho/Dependency_Resolution_Troubleshooting for help.
[ERROR] Cannot resolve dependencies of MavenProject: com.microsoft.jdtls.ext:com.microsoft.jdtls.ext.core:0.5.1 @ /mnt/a/1/s/jdtls.ext/com.microsoft.jdtls.ext.core/pom.xml: See log for details -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MavenExecutionException
[08:24:52] 'build_server' errored after 16 s
[08:24:52] Error: Command failed: mvn clean package
    at checkExecSyncError (child_process.js:629:11)
    at Object.execSync (child_process.js:666:13)
    at gulp.task (/mnt/a/1/s/gulpfile.js:16:6)
    at taskWrapper (/mnt/a/1/s/node_modules/undertaker/lib/set-task.js:13:15)
    at bound (domain.js:402:14)
    at runBound (domain.js:415:12)
    at asyncRunner (/mnt/a/1/s/node_modules/async-done/index.js:55:18)
    at process._tickCallback (internal/process/next_tick.js:61:11)
##[error]Bash exited with code '1'.
##[section]Finishing: npx gulp build_server
```

**Comment by jdneo** [comment]
Close since the CI works fine now.
