### ISSUE TITLE
Uncaught exception is throw in VS Code Developer Tools

### ISSUE THREAD

**Issue by testforstephen** [microsoft/vscode-java-dependency#176]
```javascript
TypeError: Cannot read property 'push' of null
	at module.exports.e.DependencyDataProvider.getRootNodes.n.length.n.length.a.Jdtls.getProjects.then.e.forEach.t (c:\Users\jinbwan\.vscode\extensions\vscjava.vscode-java-dependency-0.5.1\dist\extension.js:46:28099)
	at Array.forEach (<anonymous>)
	at module.exports.e.DependencyDataProvider.getRootNodes.n.length.n.length.a.Jdtls.getProjects.then.e (c:\Users\jinbwan\.vscode\extensions\vscjava.vscode-java-dependency-0.5.1\dist\extension.js:46:28071)
	at i (c:\Users\jinbwan\.vscode\extensions\vscjava.vscode-maven-0.14.2\dist\extension.js:126:21501)
	at c:\Users\jinbwan\.vscode\extensions\vscjava.vscode-maven-0.14.2\dist\extension.js:126:21845
```

**Comment by testforstephen** [comment]
This exception will cause the dependency view is hanging. (a progress bar is always scrolling in the explorer view.)
![image](https://user-images.githubusercontent.com/14052197/64394817-81028100-d08a-11e9-8af5-2ae6fe184dfd.png)

**Comment by thesparta123** [comment]
This issue occurs for me too. Once it starts the Java Dependencies view get stuck with old information and will not update. Only solution is to close and reopen VS Code for me.
