### ISSUE TITLE
Unexpected Exception: Java Model Exception: Java Model Status [lemminx does not exist]

### ISSUE THREAD

**Issue by testforstephen** [microsoft/vscode-java-dependency#244]
Open https://github.com/eclipse/lemminx on VS Code, click lemmix node in Java dependencies view, i also see the same exception threw by dependency plugin.

```
[Error - 6:44:09 PM] 16-Mar-2020 6:44:09 PM Error in calling delegate command handler
lemminx does not exist
Java Model Exception: Java Model Status [lemminx does not exist]
	at org.eclipse.jdt.internal.core.JavaElement.newJavaModelException(JavaElement.java:583)
	at org.eclipse.jdt.internal.core.Openable.generateInfos(Openable.java:256)
	at org.eclipse.jdt.internal.core.Openable.openAncestors(Openable.java:530)
	at org.eclipse.jdt.internal.core.Openable.generateInfos(Openable.java:250)
	at org.eclipse.jdt.internal.core.JavaElement.openWhenClosed(JavaElement.java:596)
	at org.eclipse.jdt.internal.core.JavaElement.getElementInfo(JavaElement.java:326)
	at org.eclipse.jdt.internal.core.JavaElement.getElementInfo(JavaElement.java:312)
	at org.eclipse.jdt.internal.core.PackageFragmentRoot.getKind(PackageFragmentRoot.java:530)
	at com.microsoft.jdtls.ext.core.model.PackageNode.createNodeForPackageFragmentRoot(PackageNode.java:168)
	at com.microsoft.jdtls.ext.core.PackageCommand.resolvePath(PackageCommand.java:136)
	at com.microsoft.jdtls.ext.core.CommandHandler.executeCommand(CommandHandler.java:33)
	at org.eclipse.jdt.ls.core.internal.handlers.WorkspaceExecuteCommandHandler$1.run(WorkspaceExecuteCommandHandler.java:215)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:45)
	at org.eclipse.jdt.ls.core.internal.handlers.WorkspaceExecuteCommandHandler.executeCommand(WorkspaceExecuteCommandHandler.java:205)
	at org.eclipse.jdt.ls.core.internal.handlers.JDTLanguageServer.lambda$3(JDTLanguageServer.java:485)
	at org.eclipse.jdt.ls.core.internal.handlers.JDTLanguageServer.lambda$48(JDTLanguageServer.java:977)
	at java.util.concurrent.CompletableFuture.uniApply(CompletableFuture.java:602)
	at java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:577)
	at java.util.concurrent.CompletableFuture$Completion.exec(CompletableFuture.java:443)
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)
``` 

_Originally posted by @testforstephen in https://github.com/eclipse/eclipse.jdt.ls/pull/1377#issuecomment-599951963_

**Comment by testforstephen** [comment]
```
Java Model Exception: Java Model Status [lemminx does not exist]
	at org.eclipse.jdt.internal.core.JavaElement.newNotPresentException(JavaElement.java:573)
	at org.eclipse.jdt.internal.core.JavaModelManager.getPerProjectInfoCheckExistence(JavaModelManager.java:2526)
	at org.eclipse.jdt.internal.core.JavaProject.getPerProjectInfo(JavaProject.java:2347)
	at org.eclipse.jdt.internal.core.JavaProject.getRawClasspath(JavaProject.java:2376)
	at com.microsoft.jdtls.ext.core.PackageCommand.getContainers(PackageCommand.java:239)
	at com.microsoft.jdtls.ext.core.PackageCommand.getChildren(PackageCommand.java:103)
	at com.microsoft.jdtls.ext.core.CommandHandler.executeCommand(CommandHandler.java:31)
	at org.eclipse.jdt.ls.core.internal.handlers.WorkspaceExecuteCommandHandler$1.run(WorkspaceExecuteCommandHandler.java:215)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:45)
	at org.eclipse.jdt.ls.core.internal.handlers.WorkspaceExecuteCommandHandler.executeCommand(WorkspaceExecuteCommandHandler.java:205)
	at org.eclipse.jdt.ls.core.internal.handlers.JDTLanguageServer.lambda$3(JDTLanguageServer.java:485)
	at org.eclipse.jdt.ls.core.internal.handlers.JDTLanguageServer.lambda$48(JDTLanguageServer.java:977)
	at java.util.concurrent.CompletableFuture.uniApply(CompletableFuture.java:616)
	at java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:591)
	at java.util.concurrent.CompletableFuture$Completion.exec(CompletableFuture.java:457)
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)
```

**Comment by testforstephen** [comment]
The cause is project `lemmix` is just a generic maven project, not a Java project. But the dependency view still expands its classpath like a java project. 

IMO, the dependency view should not support expanding a maven project. Besides, should provide a new icon for suck kind of generic maven project.

// @jdneo

**Comment by jdneo** [comment]
Thanks for the info.

So we have two ways to resolve this issue.

1. show the maven project node, but the node is not expandable, this is more like Eclipse's behavior:
<img width="345" alt="Screen Shot 2020-03-19 at 11 14 30 AM" src="https://user-images.githubusercontent.com/6193897/77028132-002a2780-69d3-11ea-84cd-2609fd642f03.png">


<img width="311" alt="Screen Shot 2020-03-19 at 11 15 13 AM" src="https://user-images.githubusercontent.com/6193897/77028100-ef79b180-69d2-11ea-9c7d-2c24af700beb.png">


2. do not show the non-java project node, this is more like IntelliJ's behavior:
<img width="364" alt="Screen Shot 2020-03-19 at 11 06 50 AM" src="https://user-images.githubusercontent.com/6193897/77028109-f3a5cf00-69d2-11ea-976f-27d3fbb9e4a5.png">
