### ISSUE TITLE
Explorer never refreshes

### ISSUE THREAD

**Issue by dsyer** [microsoft/vscode-java-dependency#339]
It just sits there and spins:

![image](https://user-images.githubusercontent.com/124075/94436295-2f94ca80-0194-11eb-8ace-83f3df95ba49.png)

**Comment by jdneo** [comment]
Hi @dyser, will trigger the command `Developer: Reload Window` or `Java: Clean the Java language server workspace` resolve the problem?

**Comment by dsyer** [comment]
No, I tried that. Is there anywhere I can look for error logs?

**Comment by jdneo** [comment]
### client log
You can turn the `java.trace.server` to `verbose` and see if there is error in the output channel: `Language support for Java`

### server logs
You can trigger the command `Java: Open Java Language Server log file`

// https://github.com/redhat-developer/vscode-java/wiki/Troubleshooting

**Comment by dsyer** [comment]
I see errors in the developer tools console (sorry I can't see a way to get a text version of this):

![image](https://user-images.githubusercontent.com/124075/94527245-99fa4900-022e-11eb-9512-45936ef94d97.png)

![image](https://user-images.githubusercontent.com/124075/94527383-cc0bab00-022e-11eb-9565-02d06b13cdb9.png)


Similar looking logs show up in the "Language Support for Java" output with `java.trace.server=verbose`:

```
[Trace - 8:41:58 AM] Sending request 'workspace/executeCommand - (37)'.
Params: {
    "command": "java.resolvePath",
    "arguments": [
        "file:///home/dsyer/dev/boot/spring-init/samples/func/src/main/java/app/main/SampleApplication.java"
    ]
}


[Trace - 8:41:58 AM] Received response 'workspace/executeCommand - (37)' in 7ms. Request failed: No delegateCommandHandler for java.resolvePath (-32601).
[Trace - 8:41:58 AM] Sending request 'workspace/executeCommand - (38)'.
Params: {
    "command": "java.resolvePath",
    "arguments": [
        "output:extension-output-%237"
    ]
}
```

There are a couple of errors in the LS logs, but they don't look relevant:

```
!ENTRY com.microsoft.java.test.plugin 4 0 2020-09-29 08:31:07.287
!MESSAGE FrameworkEvent ERROR
!STACK 0
org.osgi.framework.BundleException: Could not resolve module: com.microsoft.java.test.plugin [145]
  Unresolved requirement: Require-Capability: osgi.ee; filter:="(&(osgi.ee=JavaSE)(version=11))"

	at org.eclipse.osgi.container.Module.start(Module.java:463)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel$2.run(ModuleContainer.java:1845)
	at org.eclipse.osgi.internal.framework.EquinoxContainerAdaptor$1$1.execute(EquinoxContainerAdaptor.java:136)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.incStartLevel(ModuleContainer.java:1838)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.incStartLevel(ModuleContainer.java:1779)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.doContainerStartLevel(ModuleContainer.java:1743)
	at org.eclipse.osgi.container.SystemModule.startWorker(SystemModule.java:269)
	at org.eclipse.osgi.container.Module.doStart(Module.java:605)
	at org.eclipse.osgi.container.Module.start(Module.java:468)
	at org.eclipse.osgi.container.SystemModule.start(SystemModule.java:193)
	at org.eclipse.osgi.internal.framework.EquinoxBundle.start(EquinoxBundle.java:439)
	at org.eclipse.osgi.internal.framework.EquinoxBundle.start(EquinoxBundle.java:458)
	at org.eclipse.osgi.launch.Equinox.start(Equinox.java:120)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.startup(EclipseStarter.java:338)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:251)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:657)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:594)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1447)
	at org.eclipse.equinox.launcher.Main.main(Main.java:1420)

!ENTRY com.microsoft.jdtls.ext.core 4 0 2020-09-29 08:31:07.291
!MESSAGE FrameworkEvent ERROR
!STACK 0
org.osgi.framework.BundleException: Could not resolve module: com.microsoft.jdtls.ext.core [143]
  Unresolved requirement: Require-Capability: osgi.ee; filter:="(&(osgi.ee=JavaSE)(version=11))"

	at org.eclipse.osgi.container.Module.start(Module.java:463)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel$2.run(ModuleContainer.java:1845)
	at org.eclipse.osgi.internal.framework.EquinoxContainerAdaptor$1$1.execute(EquinoxContainerAdaptor.java:136)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.incStartLevel(ModuleContainer.java:1838)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.incStartLevel(ModuleContainer.java:1779)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.doContainerStartLevel(ModuleContainer.java:1743)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.dispatchEvent(ModuleContainer.java:1665)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.dispatchEvent(ModuleContainer.java:1)
	at org.eclipse.osgi.framework.eventmgr.EventManager.dispatchEvent(EventManager.java:234)
	at org.eclipse.osgi.framework.eventmgr.EventManager$EventThread.run(EventManager.java:345)
```

**Comment by jdneo** [comment]
I see. It should be the same as https://github.com/microsoft/vscode-java-dependency/issues/310

Basically because the newest Java language server requires JDK11 to launch, so we also update the requirement to JDK 11 for Project Manager since the last version.

But it turns out that some users would like to still use JDK 8 so they downgrade the Java language server version. 

In #334 We've reverted the requirement to JavaSE-1.8 so the users can still use the latest Java Project Manager. (This PR will be released in the next version)

**Comment by dsyer** [comment]
Yes. It seems to work if I launch with JDK11. Thanks.

**Comment by jdneo** [comment]
You are welcome @dsyer
