### ISSUE TITLE
Cannot list projects properly with multi gradle projects workspace

### ISSUE THREAD

**Issue by testforstephen** [microsoft/vscode-java-dependency#424]
Here is a sample to reproduce the issue. You need to install [vscode-java@0.73.0](https://download.jboss.org/jbosstools/jdt.ls/staging/java-0.73.0-19.vsix) as well.
[TestGradle.zip](https://github.com/microsoft/vscode-java-debug/files/5496156/TestGradle.zip)

Cannot expand the project node well.
![image](https://user-images.githubusercontent.com/14052197/102440246-df265e00-405a-11eb-9393-845cf98a9c68.png)

Exceptions:
```
!ENTRY com.microsoft.jdtls.ext.core 4 0 2020-12-17 11:14:46.168
!MESSAGE Problem load project library 
!STACK 1
Java Model Exception: Java Model Status [TestGradle does not exist]
	at org.eclipse.jdt.internal.core.JavaElement.newNotPresentException(JavaElement.java:573)
	at org.eclipse.jdt.internal.core.JavaModelManager.getPerProjectInfoCheckExistence(JavaModelManager.java:2525)
	at org.eclipse.jdt.internal.core.JavaProject.getPerProjectInfo(JavaProject.java:2382)
	at org.eclipse.jdt.internal.core.JavaProject.getRawClasspath(JavaProject.java:2411)
	at com.microsoft.jdtls.ext.core.PackageCommand.getContainers(PackageCommand.java:255)
	at com.microsoft.jdtls.ext.core.PackageCommand.getChildren(PackageCommand.java:104)
	at com.microsoft.jdtls.ext.core.CommandHandler.executeCommand(CommandHandler.java:31)
	at org.eclipse.jdt.ls.core.internal.handlers.WorkspaceExecuteCommandHandler$1.run(WorkspaceExecuteCommandHandler.java:215)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:45)
	at org.eclipse.jdt.ls.core.internal.handlers.WorkspaceExecuteCommandHandler.executeCommand(WorkspaceExecuteCommandHandler.java:205)
	at org.eclipse.jdt.ls.core.internal.handlers.JDTLanguageServer.lambda$3(JDTLanguageServer.java:497)
	at org.eclipse.jdt.ls.core.internal.BaseJDTLanguageServer.lambda$0(BaseJDTLanguageServer.java:75)
	at java.base/java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:642)
	at java.base/java.util.concurrent.CompletableFuture$Completion.exec(CompletableFuture.java:479)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:177)
!SUBENTRY 1 org.eclipse.jdt.core 4 969 2020-12-17 11:14:46.171
!MESSAGE TestGradle does not exist

!ENTRY org.eclipse.jdt.ls.core 1 0 2020-12-17 11:14:58.751
!MESSAGE >> workspace/executeCommand java.resolvePath

!ENTRY org.eclipse.jdt.ls.core 4 2 2020-12-17 11:14:58.784
!MESSAGE Problems occurred when invoking code from plug-in: "org.eclipse.jdt.ls.core".
!STACK 0
java.lang.NullPointerException
	at com.microsoft.jdtls.ext.core.model.PackageNode.createNodeForProject(PackageNode.java:154)
	at com.microsoft.jdtls.ext.core.PackageCommand.resolvePath(PackageCommand.java:205)
	at com.microsoft.jdtls.ext.core.CommandHandler.executeCommand(CommandHandler.java:33)
	at org.eclipse.jdt.ls.core.internal.handlers.WorkspaceExecuteCommandHandler$1.run(WorkspaceExecuteCommandHandler.java:215)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:45)
	at org.eclipse.jdt.ls.core.internal.handlers.WorkspaceExecuteCommandHandler.executeCommand(WorkspaceExecuteCommandHandler.java:205)
	at org.eclipse.jdt.ls.core.internal.handlers.JDTLanguageServer.lambda$3(JDTLanguageServer.java:497)
	at org.eclipse.jdt.ls.core.internal.BaseJDTLanguageServer.lambda$0(BaseJDTLanguageServer.java:75)
	at java.base/java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:642)
	at java.base/java.util.concurrent.CompletableFuture$Completion.exec(CompletableFuture.java:479)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:177)

!ENTRY org.eclipse.jdt.ls.core 4 0 2020-12-17 11:14:58.786
!MESSAGE Error in calling delegate command handler
!STACK 0
java.lang.NullPointerException
	at com.microsoft.jdtls.ext.core.model.PackageNode.createNodeForProject(PackageNode.java:154)
	at com.microsoft.jdtls.ext.core.PackageCommand.resolvePath(PackageCommand.java:205)
	at com.microsoft.jdtls.ext.core.CommandHandler.executeCommand(CommandHandler.java:33)
	at org.eclipse.jdt.ls.core.internal.handlers.WorkspaceExecuteCommandHandler$1.run(WorkspaceExecuteCommandHandler.java:215)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:45)
	at org.eclipse.jdt.ls.core.internal.handlers.WorkspaceExecuteCommandHandler.executeCommand(WorkspaceExecuteCommandHandler.java:205)
	at org.eclipse.jdt.ls.core.internal.handlers.JDTLanguageServer.lambda$3(JDTLanguageServer.java:497)
	at org.eclipse.jdt.ls.core.internal.BaseJDTLanguageServer.lambda$0(BaseJDTLanguageServer.java:75)
	at java.base/java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:642)
	at java.base/java.util.concurrent.CompletableFuture$Completion.exec(CompletableFuture.java:479)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:177)

```

**Comment by jdneo** [comment]
So this issue contains two bug.

The first one is about `Java Model Status [TestGradle does not exist]`, which should be related with handling multi-module project. I'll raise a PR for that.

The second one is NPE in `resolvePath()`, which I think should have been resolved in #417, which will be released in next version.
