### ISSUE TITLE
No JAVA PACKAGES explorer sidebar on symlink folders

### ISSUE THREAD

**Issue by rubensa** [Microsoft/vscode-java-dependency#77]
I can't see the **JAVA PACKAGES** explorer sidebar showed in doc.  I can see a **JAVA DEPENDENCIES** sidebar that is always empty (except for multi-project workspace where I can see folder with project names but empty inside those folders).
![screenshot from 2018-10-24 15-28-27](https://user-images.githubusercontent.com/1469340/47434304-96d4c380-d7a2-11e8-9ffb-b45d587fd145.png)

The attached image is for a just created java project using command **Java:Create Java Project**.

**OS**: Linux 4.15.0-38-generic Ubuntu SMP Wed Oct 10 10:59:38 UTC 2018 x86_64 x86_64 x86_64 
GNU/Linux

| Extension | Version |
|-------------|-----------|
| vscjava.vscode-java-dependency | 0.1.0 |
| redhat.java | 0.33.0 |

**Comment by yaohaizh** [comment]
@andxu, please take a look at this issue.

**Comment by rubensa** [comment]
Done, but looks there is no error there, only java.project.list command executed.
```
!SESSION 2018-10-25 07:53:35.459 -----------------------------------------------
eclipse.buildId=unknown
java.version=1.8.0_181
java.vendor=Oracle Corporation
BootLoader constants: OS=linux, ARCH=x86_64, WS=gtk, NL=en_US
Command-line arguments:  -data /home/rubensa/development/vscode/1.28.2/config/User/workspaceStorage/4ed6ebcfcce1f690085838ca0c4c8cf4/redhat.java/jdt_ws

!ENTRY org.eclipse.jdt.ls.core 1 0 2018-10-25 07:53:48.089
!MESSAGE class org.eclipse.jdt.ls.core.internal.JavaLanguageServerPlugin is started

!ENTRY org.eclipse.jdt.ls.core 1 0 2018-10-25 07:53:51.506
!MESSAGE Main thread is waiting

!ENTRY org.eclipse.jdt.ls.core 1 0 2018-10-25 07:53:51.605
!MESSAGE >> initialize

!ENTRY org.eclipse.jdt.ls.core 1 0 2018-10-25 07:53:51.605
!MESSAGE Initializing Java Language Server 0.27.0.201810230509

!ENTRY org.eclipse.jdt.ls.core 1 0 2018-10-25 07:53:52.204
!MESSAGE >> initialized

!ENTRY org.eclipse.jdt.ls.core 1 0 2018-10-25 07:53:53.897
!MESSAGE Creating the default Java project

!ENTRY org.eclipse.jdt.ls.core 1 0 2018-10-25 07:53:54.665
!MESSAGE Finished creating the default Java project

!ENTRY org.eclipse.jdt.ls.core 1 0 2018-10-25 07:53:55.451
!MESSAGE Importing Eclipse project(s)

!ENTRY org.eclipse.jdt.ls.core 1 0 2018-10-25 07:53:55.747
!MESSAGE Workspace initialized in 4135ms

!ENTRY org.eclipse.jdt.ls.core 1 0 2018-10-25 07:53:56.400
!MESSAGE >> workspace/didChangeConfiguration

!ENTRY org.eclipse.jdt.ls.core 1 0 2018-10-25 07:53:56.401
!MESSAGE >> registerFeature 'workspace/didChangeWatchedFiles'

!ENTRY org.eclipse.jdt.ls.core 1 0 2018-10-25 07:53:56.402
!MESSAGE >> registerFeature 'workspace/didChangeWatchedFiles'

!ENTRY org.eclipse.jdt.ls.core 1 0 2018-10-25 07:53:56.411
!MESSAGE >>New configuration: {java={decompiler={fernflower={}, cfr={}, procyon=null}, home=null, jdt={ls={vmargs=-noverify -Xmx1G -XX:+UseG1GC -XX:+UseStringDeduplication}}, errors={incompleteClasspath={severity=warning}}, configuration={updateBuildConfiguration=interactive, maven={userSettings=null}}, trace={server=off}, import={gradle={enabled=true}, maven={enabled=true}, exclusions=[**/node_modules/**, **/.metadata/**, **/archetype-resources/**, **/META-INF/maven/**]}, referencesCodeLens={enabled=false}, signatureHelp={enabled=false}, implementationsCodeLens={enabled=false}, format={enabled=true, settings={url=null, profile=null}, comments={enabled=true}, onType={enabled=true}}, saveActions={organizeImports=false}, contentProvider={preferred=null}, autobuild={enabled=true}, completion={enabled=true, overwrite=true, guessMethodArguments=false, favoriteStaticMembers=[org.junit.Assert.*, org.junit.Assume.*, org.junit.jupiter.api.Assertions.*, org.junit.jupiter.api.Assumptions.*, org.junit.jupiter.api.DynamicContainer.*, org.junit.jupiter.api.DynamicTest.*, org.mockito.Mockito.*, org.mockito.ArgumentMatchers.*, org.mockito.Answers.*], importOrder=[java, javax, com, org]}, progressReports={enabled=true}, debug={logLevel=warn, settings={showHex=false, showStaticVariables=true, showQualifiedNames=false, maxStringLength=0.0, enableHotCodeReplace=true}}, dependency={showOutline=true, syncWithFolderExplorer=true}, test={report={position=sideView}}}}

!ENTRY org.eclipse.jdt.ls.core 1 0 2018-10-25 07:53:56.413
!MESSAGE >> document/didOpen

!ENTRY org.eclipse.jdt.ls.core 1 0 2018-10-25 07:53:58.828
!MESSAGE begin problem for /App.java

!ENTRY org.eclipse.jdt.ls.core 1 0 2018-10-25 07:53:58.828
!MESSAGE 0 problems reported for /App.java

!ENTRY org.eclipse.jdt.ls.core 1 0 2018-10-25 07:53:58.829
!MESSAGE Reconciled 0, validated: 1. Took 514 ms

!ENTRY org.eclipse.jdt.ls.core 1 0 2018-10-25 07:53:59.976
!MESSAGE >> workspace/executeCommand java.project.list

!ENTRY org.eclipse.jdt.ls.core 1 0 2018-10-25 07:54:07.013
!MESSAGE >> workspace/executeCommand vscode.java.test.search.all

!ENTRY org.eclipse.jdt.ls.core 1 0 2018-10-25 07:54:07.014
!MESSAGE >> workspace/executeCommand sts.java.addClasspathListener

!ENTRY org.eclipse.jdt.ls.core 1 0 2018-10-25 07:54:07.421
!MESSAGE >> workspace/executeCommand vscode.java.test.project.info

!ENTRY org.eclipse.jdt.ls.core 1 0 2018-10-25 07:54:14.287
!MESSAGE >> workspace/didChangeConfiguration

!ENTRY org.eclipse.jdt.ls.core 1 0 2018-10-25 07:54:14.288
!MESSAGE >> registerFeature 'workspace/didChangeWatchedFiles'

!ENTRY org.eclipse.jdt.ls.core 1 0 2018-10-25 07:54:14.298
!MESSAGE >>New configuration: {java={decompiler={fernflower={}, cfr={}, procyon=null}, home=null, jdt={ls={vmargs=-noverify -Xmx1G -XX:+UseG1GC -XX:+UseStringDeduplication}}, errors={incompleteClasspath={severity=warning}}, configuration={updateBuildConfiguration=interactive, maven={userSettings=null}}, trace={server=verbose}, import={gradle={enabled=true}, maven={enabled=true}, exclusions=[**/node_modules/**, **/.metadata/**, **/archetype-resources/**, **/META-INF/maven/**]}, referencesCodeLens={enabled=false}, signatureHelp={enabled=false}, implementationsCodeLens={enabled=false}, format={enabled=true, settings={url=null, profile=null}, comments={enabled=true}, onType={enabled=true}}, saveActions={organizeImports=false}, contentProvider={preferred=null}, autobuild={enabled=true}, completion={enabled=true, overwrite=true, guessMethodArguments=false, favoriteStaticMembers=[org.junit.Assert.*, org.junit.Assume.*, org.junit.jupiter.api.Assertions.*, org.junit.jupiter.api.Assumptions.*, org.junit.jupiter.api.DynamicContainer.*, org.junit.jupiter.api.DynamicTest.*, org.mockito.Mockito.*, org.mockito.ArgumentMatchers.*, org.mockito.Answers.*], importOrder=[java, javax, com, org]}, progressReports={enabled=true}, debug={logLevel=warn, settings={showHex=false, showStaticVariables=true, showQualifiedNames=false, maxStringLength=0.0, enableHotCodeReplace=true}}, dependency={showOutline=true, syncWithFolderExplorer=true}, test={report={position=sideView}}}}

!ENTRY org.eclipse.jdt.ls.core 1 0 2018-10-25 07:54:59.063
!MESSAGE >> workspace/executeCommand java.project.list

```

**Comment by andxu** [comment]
Nothing valuable found in the logs, can you take a look at the debug console in vscode by the snapshots below and then show us the java version by `java --version` so that we can replay on the same env as you btw, have you ever installed the obsolete version of java dependency(at https://marketplace.visualstudio.com/items?itemName=yaozheng.vscode-java-copilot)

![image](https://user-images.githubusercontent.com/17075863/47479868-06a98380-d861-11e8-9905-b03b378e2206.png)
![image](https://user-images.githubusercontent.com/17075863/47479874-0d37fb00-d861-11e8-89dd-f1f7443ad674.png)

**Comment by rubensa** [comment]
I've never installed that extension (I can tell you all installed extensions if needed).

```bash
> java -version
java version "1.8.0_181"
Java(TM) SE Runtime Environment (build 1.8.0_181-b13)
Java HotSpot(TM) 64-Bit Server VM (build 25.181-b13, mixed mode)
```
**Developer Tools Console Log**:
```
log.ts:159  INFO no standard startup: not a new window
TMSyntax.ts:47 Overwriting grammar scope name to file mapping for scope source.groovy.
Old grammar file: file:///media/data/rubensa/software/VSCode-linux-x64_1.28.2/resources/app/extensions/groovy/syntaxes/groovy.tmLanguage.json.
New grammar file: file:///home/rubensa/development/vscode/1.28.2/extensions/naco-siren.gradle-language-0.2.3/syntaxes/groovy.tmLanguage.json
e.register @ TMSyntax.ts:47
TMSyntax.ts:47 Overwriting grammar scope name to file mapping for scope source.yaml.
Old grammar file: file:///media/data/rubensa/software/VSCode-linux-x64_1.28.2/resources/app/extensions/yaml/syntaxes/yaml.tmLanguage.json.
New grammar file: file:///home/rubensa/development/vscode/1.28.2/extensions/pivotal.vscode-concourse-1.0.0/yaml-support/yaml.tmLanguage
e.register @ TMSyntax.ts:47
TMSyntax.ts:47 Overwriting grammar scope name to file mapping for scope source.yaml.
Old grammar file: file:///home/rubensa/development/vscode/1.28.2/extensions/pivotal.vscode-concourse-1.0.0/yaml-support/yaml.tmLanguage.
New grammar file: file:///home/rubensa/development/vscode/1.28.2/extensions/pivotal.vscode-manifest-yaml-1.0.0/yaml-support/yaml.tmLanguage
e.register @ TMSyntax.ts:47
TMSyntax.ts:47 Overwriting grammar scope name to file mapping for scope source.yaml.
Old grammar file: file:///home/rubensa/development/vscode/1.28.2/extensions/pivotal.vscode-manifest-yaml-1.0.0/yaml-support/yaml.tmLanguage.
New grammar file: file:///home/rubensa/development/vscode/1.28.2/extensions/pivotal.vscode-spring-boot-1.0.0/yaml-support/yaml.tmLanguage
e.register @ TMSyntax.ts:47
console.ts:136 [Extension Host] Git extension API method 'getGitPath' is deprecated.
t.log @ console.ts:136
console.ts:136 [Extension Host] 25 Oct 07:54:00 - Proposed protocol extensions loaded!
console.ts:136 [Extension Host] Settings changed! value = true
console.ts:136 [Extension Host] rejected promise not handled within 1 second
t.log @ console.ts:136
mainThreadExtensionService.ts:43 [johnstoncode.svn-scm]ENOTDIR: not a directory, scandir '/home/rubensa/development/vscode/1.28.2/config/User/workspaceStorage/4ed6ebcfcce1f690085838ca0c4c8cf4/redhat.java/jdt_ws/.metadata/.log'
e.$onExtensionRuntimeError @ mainThreadExtensionService.ts:43
mainThreadExtensionService.ts:44 Error: ENOTDIR: not a directory, scandir '/home/rubensa/development/vscode/1.28.2/config/User/workspaceStorage/4ed6ebcfcce1f690085838ca0c4c8cf4/redhat.java/jdt_ws/.metadata/.log'
	at Object.fs.readdirSync (fs.js:904:18)
	at Object.fs.readdirSync (ELECTRON_ASAR.js:608:28)
	at Model.<anonymous> (/media/data/rubensa/development/vscode/1.28.2/extensions/johnstoncode.svn-scm-1.44.2/out/model.js:220:20)
	at Generator.next (<anonymous>)
	at /media/data/rubensa/development/vscode/1.28.2/extensions/johnstoncode.svn-scm-1.44.2/out/model.js:13:71
	at new WrappedPromise (/media/data/rubensa/development/vscode/1.28.2/extensions/vscjava.vscode-java-pack-0.4.0/node_modules/async-listener/es6-wrapped-promise.js:13:18)
	at __awaiter (/media/data/rubensa/development/vscode/1.28.2/extensions/johnstoncode.svn-scm-1.44.2/out/model.js:9:12)
	at Model.tryOpenRepository (/media/data/rubensa/development/vscode/1.28.2/extensions/johnstoncode.svn-scm-1.44.2/out/model.js:177:16)
	at Model.<anonymous> (/media/data/rubensa/development/vscode/1.28.2/extensions/johnstoncode.svn-scm-1.44.2/out/decorators.js:75:84)
	at Generator.next (<anonymous>)
	at /media/data/rubensa/development/vscode/1.28.2/extensions/johnstoncode.svn-scm-1.44.2/out/decorators.js:11:71
	at new WrappedPromise (/media/data/rubensa/development/vscode/1.28.2/extensions/vscjava.vscode-java-pack-0.4.0/node_modules/async-listener/es6-wrapped-promise.js:13:18)
	at __awaiter (/media/data/rubensa/development/vscode/1.28.2/extensions/johnstoncode.svn-scm-1.44.2/out/decorators.js:7:12)
	at run (/media/data/rubensa/development/vscode/1.28.2/extensions/johnstoncode.svn-scm-1.44.2/out/decorators.js:75:27)
	at propagateAslWrapper (/media/data/rubensa/development/vscode/1.28.2/extensions/vscjava.vscode-java-pack-0.4.0/node_modules/async-listener/index.js:502:23)
	at /media/data/rubensa/development/vscode/1.28.2/extensions/vscjava.vscode-java-pack-0.4.0/node_modules/async-listener/glue.js:188:31
	at proxyWrapper (/media/data/rubensa/development/vscode/1.28.2/extensions/vscjava.vscode-java-pack-0.4.0/node_modules/async-listener/index.js:511:29)
	at /media/data/rubensa/development/vscode/1.28.2/extensions/vscjava.vscode-java-pack-0.4.0/node_modules/async-listener/index.js:539:70
	at /media/data/rubensa/development/vscode/1.28.2/extensions/vscjava.vscode-java-pack-0.4.0/node_modules/async-listener/glue.js:188:31
	at <anonymous>
e.$onExtensionRuntimeError @ mainThreadExtensionService.ts:44
console.ts:136 [Extension Host] rejected promise not handled within 1 second
t.log @ console.ts:136
mainThreadExtensionService.ts:43 [johnstoncode.svn-scm]ENOTDIR: not a directory, scandir '/home/rubensa/development/vscode/workspace/autotriaje/prueba2/prueba2/.vscode/settings.json'
e.$onExtensionRuntimeError @ mainThreadExtensionService.ts:43
mainThreadExtensionService.ts:44 Error: ENOTDIR: not a directory, scandir '/home/rubensa/development/vscode/workspace/autotriaje/prueba2/prueba2/.vscode/settings.json'
	at Object.fs.readdirSync (fs.js:904:18)
	at Object.fs.readdirSync (ELECTRON_ASAR.js:608:28)
	at Model.<anonymous> (/media/data/rubensa/development/vscode/1.28.2/extensions/johnstoncode.svn-scm-1.44.2/out/model.js:220:20)
	at Generator.next (<anonymous>)
	at /media/data/rubensa/development/vscode/1.28.2/extensions/johnstoncode.svn-scm-1.44.2/out/model.js:13:71
	at new WrappedPromise (/media/data/rubensa/development/vscode/1.28.2/extensions/vscjava.vscode-java-pack-0.4.0/node_modules/async-listener/es6-wrapped-promise.js:13:18)
	at __awaiter (/media/data/rubensa/development/vscode/1.28.2/extensions/johnstoncode.svn-scm-1.44.2/out/model.js:9:12)
	at Model.tryOpenRepository (/media/data/rubensa/development/vscode/1.28.2/extensions/johnstoncode.svn-scm-1.44.2/out/model.js:177:16)
	at Model.<anonymous> (/media/data/rubensa/development/vscode/1.28.2/extensions/johnstoncode.svn-scm-1.44.2/out/decorators.js:75:84)
	at Generator.next (<anonymous>)
	at /media/data/rubensa/development/vscode/1.28.2/extensions/johnstoncode.svn-scm-1.44.2/out/decorators.js:11:71
	at new WrappedPromise (/media/data/rubensa/development/vscode/1.28.2/extensions/vscjava.vscode-java-pack-0.4.0/node_modules/async-listener/es6-wrapped-promise.js:13:18)
	at __awaiter (/media/data/rubensa/development/vscode/1.28.2/extensions/johnstoncode.svn-scm-1.44.2/out/decorators.js:7:12)
	at run (/media/data/rubensa/development/vscode/1.28.2/extensions/johnstoncode.svn-scm-1.44.2/out/decorators.js:75:27)
	at propagateAslWrapper (/media/data/rubensa/development/vscode/1.28.2/extensions/vscjava.vscode-java-pack-0.4.0/node_modules/async-listener/index.js:502:23)
	at /media/data/rubensa/development/vscode/1.28.2/extensions/vscjava.vscode-java-pack-0.4.0/node_modules/async-listener/glue.js:188:31
	at proxyWrapper (/media/data/rubensa/development/vscode/1.28.2/extensions/vscjava.vscode-java-pack-0.4.0/node_modules/async-listener/index.js:511:29)
	at /media/data/rubensa/development/vscode/1.28.2/extensions/vscjava.vscode-java-pack-0.4.0/node_modules/async-listener/index.js:539:70
	at /media/data/rubensa/development/vscode/1.28.2/extensions/vscjava.vscode-java-pack-0.4.0/node_modules/async-listener/glue.js:188:31
	at <anonymous>
```

**Comment by rubensa** [comment]
I found file "5-Language Support for Java.log" inside logs/20181025T075146/exthost1/output_logging_20181025T075331 folder with this content:

```json
[Trace - 7:54:14 AM] Sending notification '$/setTraceNotification'.
Params: {
    "value": "verbose"
}


[Trace - 7:54:14 AM] Sending notification 'workspace/didChangeConfiguration'.
Params: {
    "settings": {
        "java": {
            "decompiler": {
                "fernflower": {},
                "cfr": {},
                "procyon": null
            },
            "home": null,
            "jdt": {
                "ls": {
                    "vmargs": "-noverify -Xmx1G -XX:+UseG1GC -XX:+UseStringDeduplication"
                }
            },
            "errors": {
                "incompleteClasspath": {
                    "severity": "warning"
                }
            },
            "configuration": {
                "updateBuildConfiguration": "interactive",
                "maven": {
                    "userSettings": null
                }
            },
            "trace": {
                "server": "verbose"
            },
            "import": {
                "gradle": {
                    "enabled": true
                },
                "maven": {
                    "enabled": true
                },
                "exclusions": [
                    "**/node_modules/**",
                    "**/.metadata/**",
                    "**/archetype-resources/**",
                    "**/META-INF/maven/**"
                ]
            },
            "referencesCodeLens": {
                "enabled": false
            },
            "signatureHelp": {
                "enabled": false
            },
            "implementationsCodeLens": {
                "enabled": false
            },
            "format": {
                "enabled": true,
                "settings": {
                    "url": null,
                    "profile": null
                },
                "comments": {
                    "enabled": true
                },
                "onType": {
                    "enabled": true
                }
            },
            "saveActions": {
                "organizeImports": false
            },
            "contentProvider": {
                "preferred": null
            },
            "autobuild": {
                "enabled": true
            },
            "completion": {
                "enabled": true,
                "overwrite": true,
                "guessMethodArguments": false,
                "favoriteStaticMembers": [
                    "org.junit.Assert.*",
                    "org.junit.Assume.*",
                    "org.junit.jupiter.api.Assertions.*",
                    "org.junit.jupiter.api.Assumptions.*",
                    "org.junit.jupiter.api.DynamicContainer.*",
                    "org.junit.jupiter.api.DynamicTest.*",
                    "org.mockito.Mockito.*",
                    "org.mockito.ArgumentMatchers.*",
                    "org.mockito.Answers.*"
                ],
                "importOrder": [
                    "java",
                    "javax",
                    "com",
                    "org"
                ]
            },
            "progressReports": {
                "enabled": true
            },
            "debug": {
                "logLevel": "warn",
                "settings": {
                    "showHex": false,
                    "showStaticVariables": true,
                    "showQualifiedNames": false,
                    "maxStringLength": 0,
                    "enableHotCodeReplace": true
                }
            },
            "dependency": {
                "showOutline": true,
                "syncWithFolderExplorer": true
            },
            "test": {
                "report": {
                    "position": "sideView"
                }
            }
        }
    }
}


[Trace - 7:54:59 AM] Sending request 'workspace/executeCommand - (5)'.
Params: {
    "command": "java.project.list",
    "arguments": [
        "file:///home/rubensa/development/vscode/workspace/autotriaje/prueba2/prueba2"
    ]
}


[Trace - 7:54:59 AM] Received response 'workspace/executeCommand - (5)' in 3ms.
Result: []


[Trace - 7:56:35 AM] Sending request 'workspace/executeCommand - (6)'.
Params: {
    "command": "java.project.list",
    "arguments": [
        "file:///home/rubensa/development/vscode/workspace/autotriaje/prueba2/prueba2"
    ]
}


[Trace - 7:56:35 AM] Received response 'workspace/executeCommand - (6)' in 5ms.
Result: []


[Trace - 7:58:58 AM] Received notification 'language/progressReport'.
Params: {
    "id": "b007e425-232c-4dcc-9646-a2c22afe64c6",
    "task": "Building workspace",
    "status": "Building workspace - 0%",
    "totalWork": 1000,
    "workDone": 0,
    "complete": false
}


[Trace - 7:58:58 AM] Received notification 'language/progressReport'.
Params: {
    "id": "b007e425-232c-4dcc-9646-a2c22afe64c6",
    "task": "Building workspace",
    "status": "Building workspace - 0%",
    "totalWork": 1000,
    "workDone": 0,
    "complete": true
}


[Trace - 8:08:43 AM] Sending request 'textDocument/codeAction - (7)'.
Params: {
    "textDocument": {
        "uri": "file:///home/rubensa/development/vscode/workspace/autotriaje/prueba2/prueba2/src/app/App.java"
    },
    "range": {
        "start": {
            "line": 0,
            "character": 0
        },
        "end": {
            "line": 0,
            "character": 0
        }
    },
    "context": {
        "diagnostics": []
    }
}


[Trace - 8:08:43 AM] Sending request 'workspace/executeCommand - (8)'.
Params: {
    "command": "java.resolvePath",
    "arguments": [
        "file:///home/rubensa/development/vscode/workspace/autotriaje/prueba2/prueba2/src/app/App.java"
    ]
}


[Trace - 8:08:43 AM] Sending request 'textDocument/documentSymbol - (9)'.
Params: {
    "textDocument": {
        "uri": "file:///home/rubensa/development/vscode/workspace/autotriaje/prueba2/prueba2/src/app/App.java"
    }
}


[Trace - 8:08:43 AM] Received response 'workspace/executeCommand - (8)' in 63ms.
Result: [
    {
        "name": "prueba2",
        "path": "/prueba2",
        "uri": "file:/media/data/rubensa/development/vscode/workspace/autotriaje/prueba2/prueba2",
        "kind": 2
    },
    {
        "entryKind": 1,
        "name": "src",
        "path": "/prueba2/src",
        "kind": 4
    },
    {
        "name": "app",
        "path": "/prueba2/src/app",
        "kind": 5
    },
    {
        "entryKind": 1,
        "name": "App.java",
        "path": "/prueba2/src/app/App.java",
        "uri": "file:///media/data/rubensa/development/vscode/workspace/autotriaje/prueba2/prueba2/src/app/App.java",
        "kind": 6
    }
]


[Trace - 8:08:43 AM] Sending request 'workspace/executeCommand - (10)'.
Params: {
    "command": "java.project.list",
    "arguments": [
        "file:///home/rubensa/development/vscode/workspace/autotriaje/prueba2/prueba2"
    ]
}


[Trace - 8:08:43 AM] Received response 'workspace/executeCommand - (10)' in 2ms.
Result: []


[Trace - 8:08:43 AM] Received response 'textDocument/codeAction - (7)' in 104ms.
Result: []


[Trace - 8:08:43 AM] Received response 'textDocument/documentSymbol - (9)' in 140ms.
Result: [
    {
        "name": "app",
        "kind": 4,
        "range": {
            "start": {
                "line": 0,
                "character": 0
            },
            "end": {
                "line": 0,
                "character": 12
            }
        },
        "selectionRange": {
            "start": {
                "line": 0,
                "character": 0
            },
            "end": {
                "line": 0,
                "character": 12
            }
        },
        "detail": "",
        "deprecated": false
    },
    {
        "name": "App",
        "kind": 5,
        "range": {
            "start": {
                "line": 2,
                "character": 0
            },
            "end": {
                "line": 6,
                "character": 1
            }
        },
        "selectionRange": {
            "start": {
                "line": 2,
                "character": 13
            },
            "end": {
                "line": 2,
                "character": 16
            }
        },
        "detail": "",
        "deprecated": false,
        "children": [
            {
                "name": "main(String[])",
                "kind": 6,
                "range": {
                    "start": {
                        "line": 3,
                        "character": 4
                    },
                    "end": {
                        "line": 5,
                        "character": 5
                    }
                },
                "selectionRange": {
                    "start": {
                        "line": 3,
                        "character": 23
                    },
                    "end": {
                        "line": 3,
                        "character": 27
                    }
                },
                "detail": " : void",
                "deprecated": false,
                "children": []
            }
        ]
    }
]


[Trace - 8:08:43 AM] Sending request 'workspace/executeCommand - (11)'.
Params: {
    "command": "vscode.java.test.fetch",
    "arguments": [
        "file:///home/rubensa/development/vscode/workspace/autotriaje/prueba2/prueba2/src/app/App.java"
    ]
}


[Trace - 8:08:43 AM] Sending request 'workspace/executeCommand - (12)'.
Params: {
    "command": "vscode.java.resolveMainMethod",
    "arguments": [
        "file:///home/rubensa/development/vscode/workspace/autotriaje/prueba2/prueba2/src/app/App.java"
    ]
}


[Trace - 8:08:43 AM] Sending request 'textDocument/codeAction - (13)'.
Params: {
    "textDocument": {
        "uri": "file:///home/rubensa/development/vscode/workspace/autotriaje/prueba2/prueba2/src/app/App.java"
    },
    "range": {
        "start": {
            "line": 6,
            "character": 1
        },
        "end": {
            "line": 6,
            "character": 1
        }
    },
    "context": {
        "diagnostics": []
    }
}


[Trace - 8:08:43 AM] Received response 'textDocument/codeAction - (13)' in 4ms.
Result: []


[Trace - 8:08:43 AM] Received response 'workspace/executeCommand - (11)' in 91ms.
Result: []


[Trace - 8:08:43 AM] Received response 'workspace/executeCommand - (12)' in 139ms.
Result: [
    {
        "range": {
            "start": {
                "line": 3,
                "character": 23
            },
            "end": {
                "line": 3,
                "character": 27
            }
        },
        "mainClass": "app.App",
        "projectName": "prueba2"
    }
]


[Trace - 9:00:09 AM] Sending request 'workspace/executeCommand - (14)'.
Params: {
    "command": "java.project.list",
    "arguments": [
        "file:///home/rubensa/development/vscode/workspace/autotriaje/prueba2/prueba2"
    ]
}


[Trace - 9:00:09 AM] Received response 'workspace/executeCommand - (14)' in 3ms.
Result: []
```

Looks like the **Java Language Server** returns **empty array** for "**java.project.list**" command (which seems to be the command send for **JAVA DEPENDENCIES** refresh).

**Comment by andxu** [comment]
Very strange why the empty array is reported, the code finding project list is at https://github.com/Microsoft/vscode-java-dependency/blob/master/jdtls.ext/com.microsoft.jdtls.ext.core/src/com/microsoft/jdtls/ext/core/ProjectCommand.java, and request and response in my machine look like:
```
[Trace - 4:39:59 PM] Sending request 'workspace/executeCommand - (2)'.
Params: {
    "command": "java.project.list",
    "arguments": [
        "file:///n%3A/1.helloworld"
    ]
}


[Trace - 4:39:59 PM] Received response 'workspace/executeCommand - (2)' in 2ms.
Result: [
    {
        "name": "1.helloworld",
        "path": "/1.helloworld",
        "uri": "file:/N:/1.helloworld",
        "kind": 2
    }
]
```

**Comment by andxu** [comment]
I cannot reproduce at Ubuntu machine:
```
[Trace - 4:48:34 PM] Sending request 'workspace/executeCommand - (25)'.
Params: {
    "command": "java.project.list",
    "arguments": [
        "file:///home/andy/test/ssss/bvcx"
    ]
}


[Trace - 4:48:34 PM] Received response 'workspace/executeCommand - (25)' in 2ms.
Result: [
    {
        "name": "bvcx",
        "path": "/bvcx",
        "uri": "file:/home/andy/test/ssss/bvcx",
        "kind": 2
    }
]
```

**Comment by andxu** [comment]
Are you using hard-link or similar links, I see two kinds of location:

file:///media/data/rubensa/development/vscode/workspace/autotriaje/prueba2
file:///home/rubensa/development/vscode/workspace/autotriaje/prueba2/prueba2

**Comment by rubensa** [comment]
Yes, /home/rubensa/development is a symlink to /media/data/rubensa/development.

```bash
> ls -la /home/rubensa/development
lrwxrwxrwx 1 rubensa rubensa 31 may 22 14:13 /home/rubensa/development -> /media/data/rubensa/development
```

But I have same configuration with Eclipse and never had a problem with that.

**Comment by andxu** [comment]
We will take a further test on your scenario, for workaround you can use a normal directory.

**Comment by rubensa** [comment]
Checked!  Without symlink folders I can see dependencies:
![screenshot from 2018-10-25 16-29-58](https://user-images.githubusercontent.com/1469340/47507873-52fdbf00-d873-11e8-83b5-d15563c7318c.png)

**Comment by andxu** [comment]
Find the ROOT cause,  https://github.com/eclipse/eclipse.jdt.ls/blob/fc6b40e58808d23a324628a1e79e50f117c534de/org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/managers/BasicFileDetector.java#L154
should use `Files.walkFileTree(dir, EnumSet.of(FileVisitOption.FOLLOW_LINKS), maxDepth, visitor);`
https://stackoverflow.com/questions/42158761/java-nio-iterate-files-in-symbolic-link

**Comment by andxu** [comment]
Fixed at language side, will keep on change the code in this repository to let symbolic link work.

**Comment by andxu** [comment]
The fix will depend on vscode-java new release(on-hold and wait for the next vscode-java release).
