### ISSUE TITLE
[Bug] - Project Explorer won't load the project

### ISSUE THREAD

**Issue by mamilic** [microsoft/vscode-java-dependency#848]
Steps to reproduce:
- Clone this repo, https://github.com/google/google-java-format/tree/master
- Open in VsCode
- Open Project Explorer

After opening the project explorer it will display that No Java projects found, however this is a Maven project, and should be loaded.

**Comment by mamilic** [comment]
Hm, it seems that real issue was importing the project. As it throws the,
`[Error - 2:28:53 PM] Aug 13, 2024, 2:28:53 PM Initialization failed 
org.eclipse.lsp4j.jsonrpc.ResponseErrorException: Cannot get non-null property 'jetbrainsPluginRepoToken' on root project 'idea_plugin' as it does not exist
java.util.concurrent.CompletionException: org.eclipse.lsp4j.jsonrpc.ResponseErrorException: Cannot get non-null property 'jetbrainsPluginRepoToken' on root project 'idea_plugin' as it does not exist
	at java.base/java.util.concurrent.CompletableFuture.reportJoin(Unknown Source)
	at java.base/java.util.concurrent.CompletableFuture.join(Unknown Source)
	at com.microsoft.gradle.bs.importer.Utils.getBuildTargetsMappedByProjectPath(Utils.java:47)
	at com.microsoft.gradle.bs.importer.GradleBuildServerProjectImporter.importProjects(GradleBuildServerProjectImporter.java:322)
	at com.microsoft.gradle.bs.importer.GradleBuildServerProjectImporter.importToWorkspace(GradleBuildServerProjectImporter.java:226)
	at org.eclipse.jdt.ls.core.internal.managers.ProjectsManager.importProjects(ProjectsManager.java:164)
	at org.eclipse.jdt.ls.core.internal.managers.ProjectsManager.initializeProjects(ProjectsManager.java:126)
	at org.eclipse.jdt.ls.core.internal.handlers.InitHandler$1.runInWorkspace(InitHandler.java:277)
	at org.eclipse.core.internal.resources.InternalWorkspaceJob.run(InternalWorkspaceJob.java:43)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)
Caused by: org.eclipse.lsp4j.jsonrpc.ResponseErrorException: Cannot get non-null property 'jetbrainsPluginRepoToken' on root project 'idea_plugin' as it does not exist`

After changing the 
`val jetbrainsPluginRepoToken: String by project` to
`val jetbrainsPluginRepoToken = "test'` the rpject was imported succsessfuly.

**Comment by jdneo** [comment]
Hi @microsoft/aims 
If your intention is to import the maven project, you can disable the gradle import setting:
![image](https://github.com/user-attachments/assets/5e37d2b4-32cc-4f42-b0f6-43d11d4b697f)
